import { Agent, Notification, Review, Transaction, WorkflowTemplate } from '@/types';

function iso(daysAgo: number) {
  return new Date(Date.now() - daysAgo * 86400000).toISOString();
}

// Deterministic pseudo-random in [0, 1), seeded by index — avoids SSR/CSR
// hydration mismatches that Math.random() would cause in module-level mock data.
function seededRandom(seed: number) {
  const x = Math.sin(seed * 999) * 10000;
  return x - Math.floor(x);
}

export const mockAgents: Agent[] = [
  {
    id: 'a1',
    slug: 'atlas-research-agent',
    name: 'Atlas Research Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=atlas-research',
    tagline: 'Deep web + academic research synthesis at scale',
    description:
      'Atlas crawls structured and unstructured sources, cross-references citations, and produces cited research briefs. Optimized for multi-hop question answering and literature reviews.',
    category: 'Research',
    capabilities: ['web-search', 'summarization', 'citation-checking', 'multi-hop-reasoning'],
    tools: ['browser', 'pdf-parser', 'vector-search'],
    mcpServers: ['mcp-web-search', 'mcp-arxiv'],
    supportedProtocols: ['CAP-1', 'REST', 'MCP'],
    supportedChains: ['Ethereum', 'Base', 'Solana'],
    supportedWorkflows: ['research-pipeline', 'market-analysis'],
    dependencies: ['embedding-service', 'search-index'],
    pricing: { model: 'per_call', amount: 0.42, currency: 'USDC', unit: 'per task' },
    performance: { successRate: 98.2, averageLatencyMs: 2400, completedJobs: 18420, uptime: 99.95 },
    reputationScore: 96,
    verification: 'verified',
    availability: 'online',
    version: '3.2.1',
    versionHistory: [
      { version: '3.2.1', notes: 'Improved citation accuracy for legal documents.', releasedAt: iso(10) },
      { version: '3.1.0', notes: 'Added multi-hop reasoning chains.', releasedAt: iso(70) },
      { version: '0.9.0', notes: 'Initial public beta.', releasedAt: iso(200) },
    ],
    apiEndpoints: [
      { method: 'POST', path: '/invoke', description: 'Run the agent against a task payload' },
      { method: 'GET', path: '/status', description: 'Retrieve current agent health and queue depth' },
    ],
    usageExamples: [
      { title: 'Basic invocation', code: "await croo.agents.invoke('atlas-research-agent', {\n  input: 'Summarize recent LLM alignment research',\n});" },
    ],
    featured: true,
    createdAt: iso(220),
  },
  {
    id: 'a2',
    slug: 'sentinel-verification-agent',
    name: 'Sentinel Verification Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=sentinel',
    tagline: 'Fact-checking and output verification for agent chains',
    description:
      'Sentinel independently verifies claims, code, and computations produced by upstream agents, flagging inconsistencies before they reach production workflows.',
    category: 'Verification',
    capabilities: ['fact-checking', 'code-review', 'schema-validation', 'anomaly-detection'],
    tools: ['static-analyzer', 'sandbox-runner'],
    mcpServers: ['mcp-code-exec'],
    supportedProtocols: ['CAP-1', 'REST'],
    supportedChains: ['Ethereum', 'Polygon'],
    supportedWorkflows: ['smart-contract-audit', 'research-pipeline'],
    dependencies: ['sandbox-runtime'],
    pricing: { model: 'per_call', amount: 0.65, currency: 'USDC', unit: 'per task' },
    performance: { successRate: 99.1, averageLatencyMs: 1800, completedJobs: 9210, uptime: 99.98 },
    reputationScore: 98,
    verification: 'enterprise',
    availability: 'online',
    version: '2.4.0',
    versionHistory: [
      { version: '2.4.0', notes: 'Added symbolic execution for edge-case detection.', releasedAt: iso(5) },
      { version: '2.0.0', notes: 'Rewrote schema validation engine.', releasedAt: iso(120) },
    ],
    apiEndpoints: [
      { method: 'POST', path: '/invoke', description: 'Verify an upstream output payload' },
    ],
    usageExamples: [
      { title: 'Verify a claim', code: "await croo.agents.invoke('sentinel-verification-agent', {\n  claim: 'Contract has no reentrancy vulnerabilities',\n});" },
    ],
    featured: true,
    createdAt: iso(300),
  },
  {
    id: 'a3',
    slug: 'nomad-planner-agent',
    name: 'Nomad Planner Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=nomad-planner',
    tagline: 'Decomposes complex goals into executable agent plans',
    description:
      'Nomad breaks down high-level objectives into ordered subtasks, assigns capability requirements, and produces a directed execution graph ready for orchestration.',
    category: 'Planning',
    capabilities: ['task-decomposition', 'dependency-graphing', 'cost-estimation'],
    tools: ['planner-core'],
    mcpServers: ['mcp-planning'],
    supportedProtocols: ['CAP-1', 'REST', 'MCP'],
    supportedChains: ['Ethereum', 'Base'],
    supportedWorkflows: ['research-pipeline', 'content-generation', 'blockchain-monitoring'],
    dependencies: ['graph-engine'],
    pricing: { model: 'per_call', amount: 0.3, currency: 'USDC', unit: 'per task' },
    performance: { successRate: 97.4, averageLatencyMs: 1200, completedJobs: 24310, uptime: 99.9 },
    reputationScore: 94,
    verification: 'verified',
    availability: 'online',
    version: '4.0.0',
    versionHistory: [{ version: '4.0.0', notes: 'New cost estimation model.', releasedAt: iso(20) }],
    apiEndpoints: [{ method: 'POST', path: '/invoke', description: 'Generate an execution plan' }],
    usageExamples: [{ title: 'Plan a task', code: "await croo.agents.invoke('nomad-planner-agent', {\n  goal: 'Launch a competitor analysis report',\n});" }],
    featured: true,
    createdAt: iso(180),
  },
  {
    id: 'a4',
    slug: 'ledger-blockchain-agent',
    name: 'Ledger Blockchain Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=ledger',
    tagline: 'On-chain data reads, monitoring, and settlement-ready payloads',
    description:
      'Ledger watches on-chain events, reads contract state, and prepares settlement payloads for future CROO CAP integration. On-chain execution is currently mocked.',
    category: 'Blockchain',
    capabilities: ['event-monitoring', 'contract-reads', 'payload-preparation'],
    tools: ['rpc-client', 'indexer'],
    mcpServers: ['mcp-chain-indexer'],
    supportedProtocols: ['CAP-1'],
    supportedChains: ['Ethereum', 'Base', 'Arbitrum', 'Solana'],
    supportedWorkflows: ['blockchain-monitoring', 'smart-contract-audit'],
    dependencies: ['rpc-provider'],
    pricing: { model: 'per_call', amount: 0.55, currency: 'USDC', unit: 'per task' },
    performance: { successRate: 96.8, averageLatencyMs: 3100, completedJobs: 15870, uptime: 99.7 },
    reputationScore: 91,
    verification: 'verified',
    availability: 'online',
    version: '1.9.3',
    versionHistory: [{ version: '1.9.3', notes: 'Added Arbitrum support.', releasedAt: iso(30) }],
    apiEndpoints: [{ method: 'POST', path: '/invoke', description: 'Read on-chain state or watch events' }],
    usageExamples: [{ title: 'Watch an address', code: "await croo.agents.invoke('ledger-blockchain-agent', {\n  chain: 'base',\n  address: '0x...',\n});" }],
    featured: false,
    createdAt: iso(260),
  },
  {
    id: 'a5',
    slug: 'lexicon-translation-agent',
    name: 'Lexicon Translation Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=lexicon',
    tagline: 'Context-aware translation across 80+ languages',
    description:
      'Lexicon performs nuanced translation while preserving tone, technical terminology, and formatting, with built-in glossary support for domain-specific vocabulary.',
    category: 'Language',
    capabilities: ['translation', 'localization', 'glossary-management'],
    tools: ['translation-core'],
    mcpServers: ['mcp-i18n'],
    supportedProtocols: ['REST', 'MCP'],
    supportedChains: [],
    supportedWorkflows: ['content-generation'],
    dependencies: [],
    pricing: { model: 'per_token', amount: 0.002, currency: 'USDC', unit: 'per 1k tokens' },
    performance: { successRate: 98.9, averageLatencyMs: 900, completedJobs: 42110, uptime: 99.96 },
    reputationScore: 95,
    verification: 'community',
    availability: 'online',
    version: '5.1.0',
    versionHistory: [{ version: '5.1.0', notes: 'Added 12 new language pairs.', releasedAt: iso(15) }],
    apiEndpoints: [{ method: 'POST', path: '/invoke', description: 'Translate text between languages' }],
    usageExamples: [{ title: 'Translate copy', code: "await croo.agents.invoke('lexicon-translation-agent', {\n  text: 'Welcome to CROO Hub',\n  target: 'ja',\n});" }],
    featured: false,
    createdAt: iso(310),
  },
  {
    id: 'a6',
    slug: 'optix-ocr-agent',
    name: 'Optix OCR Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=optix',
    tagline: 'High-accuracy document and image text extraction',
    description:
      'Optix extracts structured text and tables from scanned documents, invoices, and images, including handwriting recognition and layout preservation.',
    category: 'Document Processing',
    capabilities: ['ocr', 'table-extraction', 'handwriting-recognition'],
    tools: ['vision-model', 'layout-parser'],
    mcpServers: ['mcp-vision'],
    supportedProtocols: ['REST', 'MCP'],
    supportedChains: [],
    supportedWorkflows: ['ocr-workflow'],
    dependencies: ['vision-runtime'],
    pricing: { model: 'per_call', amount: 0.18, currency: 'USDC', unit: 'per page' },
    performance: { successRate: 97.9, averageLatencyMs: 1500, completedJobs: 31200, uptime: 99.85 },
    reputationScore: 92,
    verification: 'verified',
    availability: 'busy',
    version: '2.7.4',
    versionHistory: [{ version: '2.7.4', notes: 'Improved handwriting model accuracy.', releasedAt: iso(40) }],
    apiEndpoints: [{ method: 'POST', path: '/invoke', description: 'Extract text/tables from a document' }],
    usageExamples: [{ title: 'Extract invoice', code: "await croo.agents.invoke('optix-ocr-agent', {\n  fileUrl: 'https://.../invoice.pdf',\n});" }],
    featured: false,
    createdAt: iso(250),
  },
  {
    id: 'a7',
    slug: 'vault-storage-agent',
    name: 'Vault Storage Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=vault',
    tagline: 'Encrypted decentralized storage for agent artifacts',
    description:
      'Vault persists workflow artifacts and intermediate outputs with encryption at rest, versioning, and content-addressed retrieval.',
    category: 'Infrastructure',
    capabilities: ['encrypted-storage', 'versioning', 'content-addressing'],
    tools: ['storage-client'],
    mcpServers: ['mcp-storage'],
    supportedProtocols: ['REST', 'MCP', 'CAP-1'],
    supportedChains: ['Filecoin', 'Arweave'],
    supportedWorkflows: ['research-pipeline', 'ocr-workflow'],
    dependencies: ['encryption-service'],
    pricing: { model: 'subscription', amount: 12, currency: 'USDC', unit: 'per month' },
    performance: { successRate: 99.5, averageLatencyMs: 600, completedJobs: 51230, uptime: 99.99 },
    reputationScore: 97,
    verification: 'enterprise',
    availability: 'online',
    version: '3.0.2',
    versionHistory: [{ version: '3.0.2', notes: 'Arweave backend added.', releasedAt: iso(60) }],
    apiEndpoints: [{ method: 'POST', path: '/store', description: 'Persist an artifact with encryption' }],
    usageExamples: [{ title: 'Store an artifact', code: "await croo.agents.invoke('vault-storage-agent', {\n  data: reportBuffer,\n});" }],
    featured: false,
    createdAt: iso(280),
  },
  {
    id: 'a8',
    slug: 'pulse-market-analysis-agent',
    name: 'Pulse Market Analysis Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=pulse',
    tagline: 'Real-time market signal aggregation and trend analysis',
    description:
      'Pulse ingests market data feeds, on-chain activity, and sentiment signals to surface trend reports and anomaly alerts for trading and research teams.',
    category: 'Analytics',
    capabilities: ['trend-analysis', 'sentiment-analysis', 'signal-aggregation'],
    tools: ['data-feed-client', 'chart-renderer'],
    mcpServers: ['mcp-market-data'],
    supportedProtocols: ['REST', 'CAP-1'],
    supportedChains: ['Ethereum', 'Solana', 'Base'],
    supportedWorkflows: ['market-analysis'],
    dependencies: ['market-data-provider'],
    pricing: { model: 'per_call', amount: 0.75, currency: 'USDC', unit: 'per report' },
    performance: { successRate: 95.6, averageLatencyMs: 2700, completedJobs: 12040, uptime: 99.6 },
    reputationScore: 89,
    verification: 'community',
    availability: 'online',
    version: '1.4.1',
    versionHistory: [{ version: '1.4.1', notes: 'Added Solana on-chain signal feed.', releasedAt: iso(8) }],
    apiEndpoints: [{ method: 'POST', path: '/invoke', description: 'Generate a market trend report' }],
    usageExamples: [{ title: 'Generate report', code: "await croo.agents.invoke('pulse-market-analysis-agent', {\n  market: 'defi',\n});" }],
    featured: true,
    createdAt: iso(150),
  },
  {
    id: 'a9',
    slug: 'forge-content-agent',
    name: 'Forge Content Generation Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=forge',
    tagline: 'Long-form and structured content generation with brand voice',
    description:
      'Forge produces blog posts, technical docs, and marketing copy tuned to a configurable brand voice, with built-in SEO and readability scoring.',
    category: 'Content',
    capabilities: ['long-form-writing', 'seo-optimization', 'tone-adaptation'],
    tools: ['writing-core', 'seo-analyzer'],
    mcpServers: ['mcp-content'],
    supportedProtocols: ['REST', 'MCP'],
    supportedChains: [],
    supportedWorkflows: ['content-generation'],
    dependencies: [],
    pricing: { model: 'per_token', amount: 0.0015, currency: 'USDC', unit: 'per 1k tokens' },
    performance: { successRate: 96.3, averageLatencyMs: 2100, completedJobs: 28710, uptime: 99.8 },
    reputationScore: 90,
    verification: 'verified',
    availability: 'online',
    version: '6.2.0',
    versionHistory: [{ version: '6.2.0', notes: 'New brand-voice tuning presets.', releasedAt: iso(12) }],
    apiEndpoints: [{ method: 'POST', path: '/invoke', description: 'Generate long-form content' }],
    usageExamples: [{ title: 'Draft a blog post', code: "await croo.agents.invoke('forge-content-agent', {\n  topic: 'Agent orchestration best practices',\n});" }],
    featured: false,
    createdAt: iso(140),
  },
  {
    id: 'a10',
    slug: 'warden-security-agent',
    name: 'Warden Security Audit Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=warden',
    tagline: 'Automated smart contract vulnerability scanning',
    description:
      'Warden scans Solidity and Rust smart contracts for known vulnerability classes, gas inefficiencies, and access-control issues, producing a structured audit report.',
    category: 'Security',
    capabilities: ['vulnerability-scanning', 'gas-optimization', 'access-control-review'],
    tools: ['static-analyzer', 'symbolic-executor'],
    mcpServers: ['mcp-code-exec'],
    supportedProtocols: ['REST', 'CAP-1'],
    supportedChains: ['Ethereum', 'Base', 'Arbitrum'],
    supportedWorkflows: ['smart-contract-audit'],
    dependencies: ['sandbox-runtime'],
    pricing: { model: 'per_call', amount: 4.5, currency: 'USDC', unit: 'per contract' },
    performance: { successRate: 98.7, averageLatencyMs: 5400, completedJobs: 6340, uptime: 99.9 },
    reputationScore: 97,
    verification: 'enterprise',
    availability: 'online',
    version: '2.1.0',
    versionHistory: [{ version: '2.1.0', notes: 'Added symbolic execution engine.', releasedAt: iso(25) }],
    apiEndpoints: [{ method: 'POST', path: '/invoke', description: 'Run a full contract audit' }],
    usageExamples: [{ title: 'Audit a contract', code: "await croo.agents.invoke('warden-security-agent', {\n  contractAddress: '0x...',\n  chain: 'ethereum',\n});" }],
    featured: true,
    createdAt: iso(190),
  },
  {
    id: 'a11',
    slug: 'compass-discovery-agent',
    name: 'Compass Discovery Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=compass',
    tagline: 'Meta-agent that indexes and recommends other agents',
    description:
      'Compass continuously indexes the agent marketplace, tracking capability changes and reputation shifts to power discovery recommendations across the ecosystem.',
    category: 'Meta',
    capabilities: ['agent-indexing', 'capability-matching', 'trend-detection'],
    tools: ['index-crawler'],
    mcpServers: ['mcp-registry'],
    supportedProtocols: ['CAP-1', 'REST'],
    supportedChains: [],
    supportedWorkflows: [],
    dependencies: ['registry-service'],
    pricing: { model: 'free', amount: 0, currency: 'USDC' },
    performance: { successRate: 99.9, averageLatencyMs: 400, completedJobs: 98210, uptime: 99.99 },
    reputationScore: 99,
    verification: 'enterprise',
    availability: 'online',
    version: '7.0.0',
    versionHistory: [{ version: '7.0.0', notes: 'Full registry re-index engine.', releasedAt: iso(3) }],
    apiEndpoints: [{ method: 'GET', path: '/recommend', description: 'Get recommended agents for a capability set' }],
    usageExamples: [{ title: 'Get recommendations', code: "await croo.agents.invoke('compass-discovery-agent', {\n  capabilities: ['ocr', 'translation'],\n});" }],
    featured: false,
    createdAt: iso(400),
  },
  {
    id: 'a12',
    slug: 'cipher-data-agent',
    name: 'Cipher Data Extraction Agent',
    avatarUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=cipher',
    tagline: 'Structured data extraction from messy unstructured sources',
    description:
      'Cipher parses emails, PDFs, and web pages into clean structured JSON, with schema inference and confidence scoring per field.',
    category: 'Document Processing',
    capabilities: ['data-extraction', 'schema-inference', 'confidence-scoring'],
    tools: ['pdf-parser', 'html-parser'],
    mcpServers: ['mcp-vision'],
    supportedProtocols: ['REST', 'MCP'],
    supportedChains: [],
    supportedWorkflows: ['ocr-workflow', 'research-pipeline'],
    dependencies: [],
    pricing: { model: 'per_call', amount: 0.22, currency: 'USDC', unit: 'per document' },
    performance: { successRate: 96.9, averageLatencyMs: 1700, completedJobs: 19870, uptime: 99.75 },
    reputationScore: 88,
    verification: 'community',
    availability: 'offline',
    version: '1.6.2',
    versionHistory: [{ version: '1.6.2', notes: 'Improved schema inference for nested JSON.', releasedAt: iso(45) }],
    apiEndpoints: [{ method: 'POST', path: '/invoke', description: 'Extract structured data from a document' }],
    usageExamples: [{ title: 'Extract data', code: "await croo.agents.invoke('cipher-data-agent', {\n  source: 'email',\n  raw: rawEmailText,\n});" }],
    featured: false,
    createdAt: iso(230),
  },
];

export const mockReviews: Record<string, Review[]> = {
  'atlas-research-agent': [
    { id: 'r1', author: { name: 'Jordan Reyes', avatarUrl: 'https://api.dicebear.com/7.x/notionists/svg?seed=jordan-reyes' }, rating: 5, title: 'Rock solid for literature reviews', body: 'Atlas cut our research time by 70%. Citation accuracy has been flawless across 40+ briefs.', helpfulVotes: 34, createdAt: iso(12) },
    { id: 'r2', author: { name: 'Priya Nandan', avatarUrl: 'https://api.dicebear.com/7.x/notionists/svg?seed=priya-nandan' }, rating: 4, title: 'Great, occasional latency spikes', body: 'Very accurate but response time varies under heavy load. Still our default research agent.', helpfulVotes: 12, createdAt: iso(30) },
  ],
  'sentinel-verification-agent': [
    { id: 'r3', author: { name: 'Marcus Webb', avatarUrl: 'https://api.dicebear.com/7.x/notionists/svg?seed=marcus-webb' }, rating: 5, title: 'Caught a critical bug before launch', body: 'Sentinel flagged a reentrancy pattern our internal review missed. Worth every call.', helpfulVotes: 51, createdAt: iso(5) },
  ],
};

export const mockTemplates: WorkflowTemplate[] = [
  { id: 't1', slug: 'research-pipeline', name: 'Research Pipeline', description: 'Plan a research task, gather sources, verify claims, and store the final brief.', category: 'Research', icon: 'search', nodes: [], edges: [], usageCount: 812, featured: true },
  { id: 't2', slug: 'smart-contract-audit', name: 'Smart Contract Audit', description: 'Run static analysis, security scanning, and blockchain state verification on a contract.', category: 'Security', icon: 'shield', nodes: [], edges: [], usageCount: 356, featured: true },
  { id: 't3', slug: 'market-analysis', name: 'Market Analysis', description: 'Aggregate market signals, analyze trends, and generate an executive summary report.', category: 'Analytics', icon: 'trending-up', nodes: [], edges: [], usageCount: 501, featured: true },
  { id: 't4', slug: 'content-generation', name: 'Content Generation', description: 'Plan, draft, and translate long-form content across multiple languages.', category: 'Content', icon: 'pen-line', nodes: [], edges: [], usageCount: 274, featured: false },
  { id: 't5', slug: 'ocr-workflow', name: 'OCR Workflow', description: 'Extract text from scanned documents, structure the data, and persist to storage.', category: 'Document Processing', icon: 'scan-text', nodes: [], edges: [], usageCount: 198, featured: false },
  { id: 't6', slug: 'blockchain-monitoring', name: 'Blockchain Monitoring', description: 'Continuously monitor on-chain events and verify anomalies against expected state.', category: 'Blockchain', icon: 'link', nodes: [], edges: [], usageCount: 143, featured: false },
];

export const mockTransactions: Transaction[] = Array.from({ length: 14 }).map((_, i) => {
  const statuses: Transaction['status'][] = ['completed', 'completed', 'processing', 'escrow_hold', 'pending', 'failed'];
  const agent = mockAgents[i % mockAgents.length];
  const status = statuses[i % statuses.length];
  return {
    id: `tx-${i}`,
    agent: { name: agent.name, avatarUrl: agent.avatarUrl, slug: agent.slug },
    amount: Number((seededRandom(i + 1) * 25 + 0.5).toFixed(2)),
    currency: 'USDC',
    status,
    description: `Payment for ${agent.name} task execution`,
    invoiceNumber: `INV-${1000 + i}-${(i * 731).toString(36).toUpperCase()}`,
    settlementMethod: 'placeholder_offchain',
    escrow: { isEscrow: status === 'escrow_hold', releaseCondition: status === 'escrow_hold' ? 'Job completion confirmed by initiator' : undefined },
    createdAt: iso(i),
  };
});

export const mockNotifications: Notification[] = [
  { id: 'n1', type: 'workflow', title: 'Workflow run completed', body: '"Weekly Competitive Research" finished successfully with 4/4 steps passing.', isRead: false, createdAt: iso(0) },
  { id: 'n2', type: 'transaction', title: 'Payment settled', body: 'Invoice INV-1002 was marked completed for Atlas Research Agent.', isRead: false, createdAt: iso(0.2) },
  { id: 'n3', type: 'reputation', title: 'Reputation milestone reached', body: 'Sentinel Verification Agent crossed 98 reputation score.', isRead: true, createdAt: iso(1) },
  { id: 'n4', type: 'agent', title: 'New agent available', body: 'Warden Security Audit Agent is now verified and live in the marketplace.', isRead: true, createdAt: iso(2) },
  { id: 'n5', type: 'security', title: 'New sign-in detected', body: 'A new session was started from Chrome on Windows.', isRead: true, createdAt: iso(4) },
];

export const reputationHistory = Array.from({ length: 12 }).map((_, i) => ({
  month: new Date(Date.UTC(2025, i, 1)).toLocaleString('en-US', { month: 'short' }),
  score: 68 + Math.round(Math.sin(i / 2) * 6 + i * 2.2),
  jobs: 400 + i * 180 + Math.round(seededRandom(i + 10) * 100),
}));

export const revenueTrend = Array.from({ length: 12 }).map((_, i) => ({
  month: new Date(Date.UTC(2025, i, 1)).toLocaleString('en-US', { month: 'short' }),
  revenue: 4200 + i * 950 + Math.round(seededRandom(i + 20) * 800),
  transactions: 120 + i * 40,
}));

export const latencyByCategory = [
  { category: 'Research', latency: 2400 },
  { category: 'Verification', latency: 1800 },
  { category: 'Planning', latency: 1200 },
  { category: 'Blockchain', latency: 3100 },
  { category: 'OCR', latency: 1500 },
  { category: 'Security', latency: 5400 },
];

export const discoveryTrends = Array.from({ length: 8 }).map((_, i) => ({
  week: `W${i + 1}`,
  queries: 220 + i * 35 + Math.round(seededRandom(i + 30) * 40),
  hires: 60 + i * 12,
}));
